/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PROYECTO;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.DayOfWeek;
import java.time.LocalDate;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.plot.PlotOrientation;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.CLOSED_OPTION;
import javax.swing.JPanel;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author sotot
 */
public class P7_Reporte extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();

    static Connection con = null;
    static Statement stmt = null;
    static ResultSet rs = null;

    public static Connection conectar() {
        String cadena = "jdbc:sqlserver://localhost:1433;databaseName=PlazaVeaBruh3;user=sa;password=root;logingTimeout=10";
        try {
            con = DriverManager.getConnection(cadena);
            return con;
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(null, e, "No se pudo conectar", CLOSED_OPTION);
            return null;
        }
    }

    public void CATEGORIA() {
        try {
            stmt = P5_ENTRADA.conectar().createStatement();
            String motiv = "select * from TB_CATEGORIA";
            rs = stmt.executeQuery(motiv);
            while (rs.next()) {
                //PARA ESTE NO HAY NECESIDAD DE ESPECIFICAR LA COLUMNA             
                JBoxCategoria.addItem(rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(null, e, "No se pudo recuperar", CLOSED_OPTION);
        }
    }

    public void Consulta(String cate) {
        try {
            stmt = P7_Reporte.conectar().createStatement();
            String consulta = "SELECT p.NOMBRE,p.STOCK\n"
                    + "FROM TB_CATEGORIA c INNER JOIN TB_PRODUCTO p ON c.ID_CATEGORIA = p.ID_CATEGORIA\n"
                    + "WHERE c.CATEGORIA = '" + cate + "';";
            rs = stmt.executeQuery(consulta);
            while (rs.next()) {
                String Producto = rs.getString("NOMBRE");
                int Stock = rs.getInt("STOCK");

            }
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(null, e, "No se pudo recuperar", CLOSED_OPTION);
        }
    }

    public String fecha() {
        LocalDate now = LocalDate.now();
        DayOfWeek day = now.getDayOfWeek();
        //nombreDispositivonombreDispositivoint year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        int week = day.getValue();
        String[] Days = {"Lunes", "Martes", "Miercoles", "Jueves", "Vierenes", "Sabado", "Domingo"};
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre",
            "Octubre", "Noviembre", "Diciemrbre"};
        return Days[week - 1] + ", " + dia + " de " + meses[month - 1];
    }

    /**
     * Creates new form P7_Reporte
     */
    public P7_Reporte() {
        initComponents();
        setLocationRelativeTo(null);
        CATEGORIA();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTbuscar = new javax.swing.JButton();
        Fondo = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        JBoxCategoria = new javax.swing.JComboBox<>();
        Grafico = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jtpro1 = new javax.swing.JTextField();
        jtpro2 = new javax.swing.JTextField();
        jtpro3 = new javax.swing.JTextField();
        jtpro4 = new javax.swing.JTextField();
        jtcan1 = new javax.swing.JTextField();
        jtcan2 = new javax.swing.JTextField();
        jtcan3 = new javax.swing.JTextField();
        jtcan4 = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTbuscar.setText("Reporte");
        JTbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTbuscarActionPerformed(evt);
            }
        });

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("REPORTE");
        Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        JBoxCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBoxCategoriaMouseClicked(evt);
            }
        });
        Fondo.add(JBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 84, 200, -1));

        javax.swing.GroupLayout GraficoLayout = new javax.swing.GroupLayout(Grafico);
        Grafico.setLayout(GraficoLayout);
        GraficoLayout.setHorizontalGroup(
            GraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        GraficoLayout.setVerticalGroup(
            GraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        Fondo.add(Grafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 179, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Categoria");
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 52, -1, -1));
        Fondo.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 130, -1));

        jtpro1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtpro1.setBorder(null);
        Fondo.add(jtpro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 100, -1));

        jtpro2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtpro2.setBorder(null);
        Fondo.add(jtpro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 100, -1));

        jtpro3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtpro3.setBorder(null);
        Fondo.add(jtpro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 100, -1));

        jtpro4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtpro4.setBorder(null);
        Fondo.add(jtpro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 100, -1));

        jtcan1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtcan1.setBorder(null);
        Fondo.add(jtcan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jtcan2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtcan2.setBorder(null);
        Fondo.add(jtcan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jtcan3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtcan3.setBorder(null);
        Fondo.add(jtcan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 70, -1));

        jtcan4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtcan4.setBorder(null);
        Fondo.add(jtcan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 70, -1));
        Fondo.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 131, -1));

        jLabel3.setText("Producto");
        Fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabel4.setText("Cantidad");
        Fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name.setBorder(null);
        Fondo.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 120, -1));

        jButton1.setText("Graficar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(785, 785, 785)
                .addComponent(JTbuscar)
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(JTbuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTbuscarActionPerformed
        // TODO add your handling code here:
        String name = Name.getText();
        String feActual = fecha();

        int n1 = Integer.parseInt(jtcan1.getText());
        int n2 = Integer.parseInt(jtcan2.getText());
        int n3 = Integer.parseInt(jtcan3.getText());
        int n4 = Integer.parseInt(jtcan4.getText());

        String pro1 = jtpro1.getText();
        String pro2 = jtpro2.getText();
        String pro3 = jtpro3.getText();
        String pro4 = jtpro4.getText();
         String prod=JBoxCategoria.getSelectedItem().toString();

        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("C:\\Users\\sotot\\Pictures\\" + name + ".pdf"));
            document.open();

            // FUENTE
            Font font = FontFactory.getFont(FontFactory.COURIER, 12);

            // ENCABEZADO DEL PDF
            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\tEmpresa: PLAZA VEA\n", font));
            document.add(new Paragraph("\tAsunto: Reporte de consulta\n", font));
            document.add(new Paragraph("\tFecha de reporte:" + feActual + "\n", font));
            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\t_____________________________________________________________________", font));
            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\tGráfico de consulta:\n", font));
            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\n", font));

            // GENERAR GRAFICO
            DefaultCategoryDataset datos = new DefaultCategoryDataset();
            datos.setValue(n1, "Producto", pro1);
            datos.setValue(n2, "Producto", pro2);
            datos.setValue(n3, "Producto", pro3);
            datos.setValue(n4, "Producto", pro4);

            JFreeChart grafico_barras = ChartFactory.createBarChart3D(
                    "Repoerte de producto",
                    prod,
                    "Stock",
                    datos,
                    PlotOrientation.VERTICAL,
                    true,
                    true,
                    false
            );

            // CONVERTIR EL GRAFICO A IMAGEN
            int width = 400;
            int height = 200;
            BufferedImage chartImage = grafico_barras.createBufferedImage(width, height);

            // AGREGAR GRAFICO AL PDF
            com.itextpdf.text.Image image = com.itextpdf.text.Image.getInstance(chartImage, null);
            document.add(image);

            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\n", font));
            document.add(new Paragraph("\n", font));
            Paragraph centro1 = new Paragraph("\t______________________\n", font);
            centro1.setAlignment(Paragraph.ALIGN_CENTER);
            Paragraph centro2 = new Paragraph("\tFIRMA DEL ENCARGADO\n", font);
            centro2.setAlignment(Paragraph.ALIGN_CENTER);

            document.add(centro1);
            document.add(centro2);

            document.close();
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException | DocumentException ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al guardar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JTbuscarActionPerformed

    private void JBoxCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBoxCategoriaMouseClicked
//        // TODO add your handling code here:
//        String cate = JBoxCategoria.getSelectedItem().toString();
//        Consulta(cate);
//
//        try {
//            Statement statement = con.createStatement();
//            ResultSet rs = statement.executeQuery("SELECT p.NOMBRE,p.STOCK\n"
//                    + "FROM TB_CATEGORIA c INNER JOIN TB_PRODUCTO p ON c.ID_CATEGORIA = p.ID_CATEGORIA\n"
//                    + "WHERE c.CATEGORIA = '" + cate + "';");
//            while (rs.next()) {
//                String cat = rs.getString("NOMBRE");
//                Int stock = rs.getInt("STOCK");
//
//            }
//
////        try {
////             stmt = P7_Reporte.conectar().createStatement();
////             String Cat = "SELECT p.NOMBRE,p.STOCK\n"
////                + "FROM TB_CATEGORIA c INNER JOIN TB_PRODUCTO p ON c.ID_CATEGORIA = p.ID_CATEGORIA\n"
////                + "WHERE c.CATEGORIA = '" + cate + "';";
////             rs = stmt.executeQuery(Cat);
////            while (rs.next()) {
////                String Producto = rs.getString("NOMBRE");
////                int Stock = rs.getInt("STOCK");
////            }
////            ejem.setText(Producto);
////        } catch (SQLException ex) {
////            JOptionPane.showConfirmDialog(null, ex, "No se pudo recuperar", CLOSED_OPTION);
////        }
//        } catch (SQLException ex) {
//            Logger.getLogger(P7_Reporte.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_JBoxCategoriaMouseClicked
    //grfico//

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n1 = Integer.parseInt(jtcan1.getText());
        int n2 = Integer.parseInt(jtcan2.getText());
        int n3 = Integer.parseInt(jtcan3.getText());
        int n4 = Integer.parseInt(jtcan4.getText());

        String pro1 = jtpro1.getText();
        String pro2 = jtpro2.getText();
        String pro3 = jtpro3.getText();
        String pro4 = jtpro4.getText();
        String prod=JBoxCategoria.getSelectedItem().toString();

        DefaultCategoryDataset datos = new DefaultCategoryDataset();
        //datos.setValue(VARIABLE, "VALOR", "REFERENCIA");
        datos.setValue(n1, "Producto", pro1);
        datos.setValue(n2, "Producto", pro2);
        datos.setValue(n3, "Producto", pro3);
        datos.setValue(n4, "Producto", pro4);

        JFreeChart grafico_barras = ChartFactory.createBarChart3D(
                "Reporte de Producto",//NOMBRE DEL GRAFICO
                prod,//NOMBRE DE LAS BARRAS O COLUMNAS
                "Stock",//NOMBRE DE LA NUMERACION
                datos,//DATOS DEL GTRAFICO
                PlotOrientation.VERTICAL,//ORIENTACION
                true,//LEGENDA DE BARRAS INDIVIDUALES POR COLUMNA
                true,//HERRAMIENTAS
                false//URL DEL GRAFICO
        );

        ChartPanel panel = new ChartPanel(grafico_barras);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(400, 200));

        Grafico.setLayout(new BorderLayout());
        Grafico.add(panel, BorderLayout.NORTH);

        pack();
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P7_Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P7_Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P7_Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P7_Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P7_Reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Grafico;
    private javax.swing.JComboBox<String> JBoxCategoria;
    private javax.swing.JButton JTbuscar;
    private javax.swing.JTextField Name;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtcan1;
    private javax.swing.JTextField jtcan2;
    private javax.swing.JTextField jtcan3;
    private javax.swing.JTextField jtcan4;
    private javax.swing.JTextField jtpro1;
    private javax.swing.JTextField jtpro2;
    private javax.swing.JTextField jtpro3;
    private javax.swing.JTextField jtpro4;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/FONDOS/fondo2.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);

            super.paint(g);
        }
    }
}
